---
- name: join node
  command: kubeadm join --token {{ hostvars[groups['master'][0]]['kubeadm_token']['stdout'] }} {{ groups['master'][0] }}:6443 --discovery-token-ca-cert-hash {{ hostvars[groups['master'][0]]['kubeadm_hash']['stdout'] }}
